apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ops
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJza2xwb25nc2l0IiwicGFzc3dvcmQiOiJqQ0wxNTlDbnJJcnUiLCJlbWFpbCI6InBvbmdzaXRAc2tpbGxsYW5lLmNvbSIsImF1dGgiOiJjMnRzY0c5dVozTnBkRHBxUTB3eE5UbERibkpKY25VPSJ9fX0=
type: kubernetes.io/dockerconfigjson